# Generated by Django 3.2.4 on 2021-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=10)),
                ('product_cost', models.CharField(max_length=20)),
            ],
        ),
    ]
