# Generated by Django 3.2.4 on 2021-09-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='phone_num',
            new_name='pname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_cost',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='pcost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='pnum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
