# Generated by Django 3.2.4 on 2021-09-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_app', '0002_auto_20210912_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=10)),
                ('p_num', models.CharField(blank=True, max_length=10, null=True)),
                ('p_cost', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
