# Generated by Django 3.2.4 on 2021-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_app', '0004_cart1_u_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='p_cost2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
